config/routes.rb
SampleApp::Application.routes.draw do
  get "spot/index"
  resources :posts

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/spot',    to: 'static_pages#spot',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/postup',  to: 'posts#new',            via: 'get'
  match '/boarding',to: 'boarding#home',        via: 'get'
	match '/station', to: 'index#home',           via: 'get'
  match '/station', to: 'index#stationElectronicBillboards',    via: 'post'

end

app/views/index/_stationElectronicBillboards.html.erb
<!--
<ul class = "platform" style="list-style:none">
	<div class = "bound">1　新宿方面</div>
	<li class = "trainArrivedTime">16:29　各駅停車　新宿行き<span class = "board"><%= link_to "乗車する", boarding_path %></span></li>
	<li class = "trainArrivedTime">16:33　各駅停車　新宿行き<span class = "board"><%= link_to "乗車する", boarding_path %></span></li>
</ul>
<ul class = "platform" style="list-style:none">
	<div class = "bound">2　渋谷方面</div>
	<li class = "trainArrivedTimeLate"><span class = "Late">遅延</span>16:29　各駅停車　渋谷行き<span class = "board"><%= link_to "乗車する", boarding_path %></span></li>
	<li class = "trainArrivedTime">16:33　各駅停車　渋谷行き<span class = "board"><%= link_to "乗車する", boarding_path %></span></li>
</ul>
-->
<ul class = "platform" style="list-style:none">
	<% near_stations.each do |station|%>
		<div class = "stationName"><%= station.name%></div>
	        <div class = "bound">bound</div>
		<li class = "trainArrivedTime"><span class = "board"><%= link_to "乗車>する", boarding_path %></span></li>
		<div class = "stationName">test</div>
	<% end %>
</ul>


<% stationCount = 0 %>

app/views/index/_trainMap.html.erb
<!--
	<ul style="list-style:none">
 		<li class="station">代々木　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">原宿　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">渋谷　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">恵比寿　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">目黒　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">五反田　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">大崎　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">品川　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">田町　　<span class = "stationIcon">　</span></li>
		<li class = "right"></li>
		<li class="station">浜松町　<span class = "stationIcon">　</span></li>
	</ul>
-->
<% spaceCount = 6%>
<% wroteStationNumber = 0 %>
<ul style="list-style:none">
	<% stations.each do |station| %>
		<% shouldSpaceInsertNumber = spaceCount - station.name.length%>
		<% for num in 1..shouldSpaceInsertNumber do %>
			<% station.name = station.name + "　" %>
		<% end %>
		<li class="station"><%=station.name%><div class = "circle"></div></li>
		<% if wroteStationNumber != stations.length - 1%>
			<li class = "right"></li>
		<% end %>
		<% wroteStationNumber = wroteStationNumber + 1 %>
	<% end %>
</ul>

app/views/index/home.html.erb
    <script>
      // 現在地を取得する処理です。
      // 成功時にはコールバックsuccess、エラー時にはコールバックerrorが実行されます 。
      navigator.geolocation.getCurrentPosition(success, error);

      // 位置情報を取得できた場合のコールバックです。テキストボックスに緯度経度を格納します。
      function success(position) {
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;

        lon = 139.766926;
        lat = 35.681265;

        $.ajax({
          url: "/station",
          type: "POST",
          data: {lat:lat,lon:lon}
        });
        document.getElementById("position_msg").innerHTML = "デバイスの位置情報を取得しました";
      }
      // 位置情報取得失敗時のコールバックです。エラーメッセージを表示します。
      function error(error) {
        var error_msg = "";
        switch(error.code)
        {
          case error.PERMISSION_DENIED:
            error_msg = "位置情報の利用を有効にしてください";
            break;
          case error.POSITION_UNAVAILABLE:
            error_msg = "デバイスの位置が判定できませんでした";
            break;
          case error.TIMEOUT:
            error_msg = "位置情報の取得にタイムアウトしました";
            break;
        }
        document.getElementById("position_msg").innerHTML = error_msg;
      }
    </script>

<div id="position_msg" style="margin-top:10px;"></div>

<div id = "stationInformation">
	<div id = "stationElectronicBillboards">
		<%= render partial: 'index/stationElectronicBillboards',locals: { near_stations: [] }%>
	</div>

	<div id = "trainlocationMap">
  <%= render 'shared/map' %>
	</div>
</div>

<div id = "trainMap">
  <%= render partial: 'index/trainMap',locals: { stations: [] }%>
</div>

app/views/index/stationElectronicBillboards.js.erb
$("#stationElectronicBillboards").html("<%= escape_javascript(render partial: 'index/stationElectronicBillboards', locals: { near_stations: @near_stations2 } ) %>"); 

$("#trainMap").html("<%= escape_javascript(render partial: 'index/trainMap', locals: { stations: @near_stations2 } ) %>")

app/views/index/trainMap.js.erb
$("#trainMap").html("<%= escape_javascript(render partial: 'index/trainMap', locals: { stations: @near_stations2 } ) %>")